### PR TITLE
upgrade singer-python to be compatible with zenpy pytz required version

### PR DESCRIPTION
**Pull request by cscott20**

### CODE REVIEW

**Comment by askedrelic** [comment]
Here is the changelog - I think this looks fine; minimal changes https://github.com/singer-io/singer-python/blob/master/CHANGELOG.md

@benekastah have you upgraded singer before? Anything to watch for?

**Review by askedrelic — APPROVED** [review]

**Comment by benekastah** [comment]
Sorry, didn't mean to let this slip.

Se we have our own fork of singer: https://github.com/Pathlight/singer-python. @cscott20 here's what needs to happen:
- Clone our singer repo, create a feature branch
- On the feature branch merge in the latest `5.12.x` version from the upstream repo
- Create a PR to sanity check the changes
- Once merged, go to master, pull, and do `git tag v5.12.x && git push --tags` (replace the x with the actual version number).

The fork has a few commits of our own on it, most notably that it automatically selects all streams.

**Review by benekastah — CHANGES_REQUESTED** [review]
.

**Comment by cscott20** [comment]
Going to close this PR for now and go through the steps that Paul recommended when I have the time

**Pull request closed without merging**
